on: 
  push:
    branches:
      - main
    paths:
      - '**.json'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    if: ${{ github.repository_owner == 'RedLime' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test work
        uses: ./
        id: test
        with: 
          base-path: './test'
          editable-files-path: 'resources'
      - name: Commit update lang files
        uses: endbug/add-and-commit@v9
        with:
          add: './test'
          message: 'chore: update lang files'
          default_author: github_actions