on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    if: ${{ !contains(github.event.head_commit.message, 'chore:') }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Test work
        uses: ./
        id: test
        with: 
          base-path: './test'
      - name: Commit update lang files
        uses: EndBug/add-and-commit@v9
        with:
          add: '*.json --force'
          message: 'chore: update lang files'